# -*- coding: utf-8 -*-
"""Applied(Hybrid model of shallow cnn and VGG16 TL).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXYNt3k5F5sz70Ggoep8yji1VBr8JPpv

**1. Import Libraries & Mount Drive**
"""

import zipfile
import os
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from skimage.feature import hog

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# For deep learning
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping

from google.colab import drive
drive.mount('/content/drive')

"""**2. Parameters and Data Extraction**"""

zip_path = '/content/drive/MyDrive/pneumonia/archive (1).zip'
extract_to = './unzipped_dataset'
img_size = (64, 64)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

"""
**3. Load Images and Labels**"""

X, y = [], []
class_names = []
class_to_idx = {}

for root, dirs, files in os.walk(extract_to):
    image_files = [f for f in files if os.path.isfile(os.path.join(root, f)) and f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tiff'))]
    if not image_files:
        continue
    class_name = os.path.basename(root)
    if class_name not in ['NORMAL', 'PNEUMONIA']:
        continue
    if class_name not in class_to_idx:
        class_to_idx[class_name] = len(class_names)
        class_names.append(class_name)
    label = class_to_idx[class_name]
    for fname in image_files:
        if fname.startswith('._'):
            continue
        img_path = os.path.join(root, fname)
        try:
            img = Image.open(img_path).convert('L')
            img = img.resize(img_size)
            X.append(np.array(img).flatten())
            y.append(label)
        except Exception as e:
            print(f"Error loading {img_path}: {e}")
print(f"Total images loaded: {len(X)}")

X = np.array(X)
y = np.array(y)

"""**4. Split Dataset**"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""**5. Data Augmentation and Preprocessing for CNN**"""

X_train_cnn = X_train.reshape(-1, img_size[0], img_size[1], 1) / 255.0
X_test_cnn = X_test.reshape(-1, img_size[0], img_size[1], 1) / 255.0
y_train_cat = tf.keras.utils.to_categorical(y_train, num_classes=len(class_names))
y_test_cat = tf.keras.utils.to_categorical(y_test, num_classes=len(class_names))

datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    fill_mode='nearest'
)
datagen.fit(X_train_cnn)

"""**6. Shallow CNN Model with Dropout and Early Stopping**

"""

early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

cnn_model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(img_size[0], img_size[1], 1)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(class_names), activation='softmax')
])

cnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

cnn_history = cnn_model.fit(
    datagen.flow(X_train_cnn, y_train_cat, batch_size=32),
    steps_per_epoch=len(X_train_cnn) // 32,
    epochs=15,
    validation_data=(X_test_cnn, y_test_cat),
    callbacks=[early_stop]
)

"""**7. Confusion Matrix for CNN**"""

cnn_pred = np.argmax(cnn_model.predict(X_test_cnn), axis=1)
print("CNN Accuracy:", accuracy_score(y_test, cnn_pred))
print(classification_report(y_test, cnn_pred, target_names=class_names))
cm = confusion_matrix(y_test, cnn_pred)
sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix: Shallow CNN')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

"""**8. Transfer Learning with VGG16 and Fine-Tuning**"""

X_train_rgb = np.stack([np.stack([im.reshape(img_size)]*3, axis=-1) for im in X_train])
X_test_rgb = np.stack([np.stack([im.reshape(img_size)]*3, axis=-1) for im in X_test])

base_model = VGG16(weights='imagenet', include_top=False, input_shape=(64, 64, 3))
base_model.trainable = False

tl_model = models.Sequential([
    base_model,
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(class_names), activation='softmax')
])

tl_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Initial training (frozen base)
tl_history = tl_model.fit(
    datagen.flow(preprocess_input(X_train_rgb.astype(np.float32)), y_train_cat, batch_size=32),
    steps_per_epoch=len(X_train_rgb) // 32,
    epochs=10,
    validation_data=(preprocess_input(X_test_rgb.astype(np.float32)), y_test_cat),
    callbacks=[early_stop]
)

# Optional: Fine-tune top layers
base_model.trainable = True
for layer in base_model.layers[:-4]:
    layer.trainable = False

tl_model.compile(optimizer=tf.keras.optimizers.Adam(1e-5), loss='categorical_crossentropy', metrics=['accuracy'])
tl_model.fit(
    datagen.flow(preprocess_input(X_train_rgb.astype(np.float32)), y_train_cat, batch_size=32),
    steps_per_epoch=len(X_train_rgb) // 32,
    epochs=5,
    validation_data=(preprocess_input(X_test_rgb.astype(np.float32)), y_test_cat),
    callbacks=[early_stop]
)

"""**9. Confusion Matrix for VGG16 Transfer Learning**"""

tl_pred = np.argmax(tl_model.predict(preprocess_input(X_test_rgb.astype(np.float32))), axis=1)
print("VGG16 Transfer Learning Accuracy:", accuracy_score(y_test, tl_pred))
print(classification_report(y_test, tl_pred, target_names=class_names))
cm = confusion_matrix(y_test, tl_pred)
sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix: VGG16 Transfer Learning')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

"""**Model comparison**"""

import matplotlib.pyplot as plt

model_names = [
     "Shallow CNN", "VGG16 Transfer"
]
accuracies = [accuracy_score(y_test, cnn_pred),accuracy_score(y_test, tl_pred)]

plt.figure(figsize=(10,6))
plt.bar(model_names, accuracies, color='skyblue')
plt.ylabel('Accuracy')
plt.title('Model Comparison')
plt.ylim(0.9, 1.0)
plt.xticks(rotation=30)
plt.show()

# For shallow CNN (grayscale input)
cnn_probs = cnn_model.predict(X_test_cnn)  # shape: (num_samples, num_classes)

# For VGG16 TL (RGB input, preprocessed)
from tensorflow.keras.applications.vgg16 import preprocess_input
tl_probs = tl_model.predict(preprocess_input(X_test_rgb.astype(np.float32)))

# Ensemble: Soft voting (average predicted probabilities) ---
ensemble_probs = (cnn_probs + tl_probs) / 2

# Final hybrid prediction: class with highest average probability
ensemble_pred = np.argmax(ensemble_probs, axis=1)

#Evaluation ---
print("Hybrid Model (Ensemble) Accuracy:", accuracy_score(y_test, ensemble_pred))
print(classification_report(y_test, ensemble_pred, target_names=class_names))

cm = confusion_matrix(y_test, ensemble_pred)
sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix: Hybrid Model (Shallow CNN + VGG16 TL)')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()