# -*- coding: utf-8 -*-
"""new full modified code including shap, lime & gradcam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qu1RZ7nNNtr4XLKjkpH6mScmL-8dSwmq

# **SECTION 1: Data Loading + Model Definitions (CNN, VGG16 TL)**

1. IMPORT LIBRARIES AND MOUNT DRIVE
"""

import zipfile
import os
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import VGG16
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

"""2. DATA EXTRACTION AND PREPROCESSING"""

zip_path = '/content/drive/MyDrive/pneumonia/archive (1).zip'
extract_to = './unzipped_dataset'
img_size = (64, 64)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

# Load images and labels
X, y = [], []
class_names = []
class_to_idx = {}

for root, dirs, files in os.walk(extract_to):
    image_files = [f for f in files if os.path.isfile(os.path.join(root, f)) and f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tiff'))]
    if not image_files:
        continue
    class_name = os.path.basename(root)
    if class_name not in ['NORMAL', 'PNEUMONIA']:
        continue
    if class_name not in class_to_idx:
        class_to_idx[class_name] = len(class_names)
        class_names.append(class_name)
    label = class_to_idx[class_name]
    for fname in image_files:
        if fname.startswith('._'):
            continue
        img_path = os.path.join(root, fname)
        try:
            img = Image.open(img_path).convert('L')
            img = img.resize(img_size)
            X.append(np.array(img).flatten())
            y.append(label)
        except Exception as e:
            print(f"Error loading {img_path}: {e}")
print(f"Total images loaded: {len(X)}")

X = np.array(X)
y = np.array(y)

# Split Dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Preprocess data for CNN
X_train_cnn = X_train.reshape(-1, img_size[0], img_size[1], 1) / 255.0
X_test_cnn = X_test.reshape(-1, img_size[0], img_size[1], 1) / 255.0
y_train_cat = tf.keras.utils.to_categorical(y_train, num_classes=len(class_names))
y_test_cat = tf.keras.utils.to_categorical(y_test, num_classes=len(class_names))

"""3. CNN MODEL DEFINITION (Functional API)"""

from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.models import Model

cnn_input = Input(shape=(64, 64, 1))

x = Conv2D(32, (3, 3), activation='relu', name="conv2d")(cnn_input)
x = MaxPooling2D()(x)
x = Conv2D(64, (3, 3), activation='relu', name="conv2d_1")(x)
x = MaxPooling2D()(x)
x = Flatten()(x)
x = Dense(64, activation='relu')(x)
x = Dropout(0.5)(x)
cnn_output = Dense(len(class_names), activation='softmax')(x)

cnn_model_func = Model(inputs=cnn_input, outputs=cnn_output)
cnn_model_func.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

"""4. VGG16 TRANSFER LEARNING MODEL DEFINITION (Functional API)"""

vgg_backbone = VGG16(weights="imagenet", include_top=False, input_shape=(64, 64, 3))
vgg_backbone.trainable = False

v = Flatten()(vgg_backbone.output)
v = Dense(128, activation='relu')(v)
v = Dropout(0.5)(v)
vgg_output = Dense(len(class_names), activation='softmax')(v)

vgg_model_func = Model(inputs=vgg_backbone.input, outputs=vgg_output)
vgg_model_func.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

"""5. DATA AUGMENTATION FOR CNN TRAINING"""

datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    fill_mode='nearest'
)
datagen.fit(X_train_cnn)

early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

"""# **SECTION 2: Training + Evaluation + Ensemble**

6. CNN MODEL TRAINING
"""

cnn_history = cnn_model_func.fit(
    datagen.flow(X_train_cnn, y_train_cat, batch_size=32),
    steps_per_epoch=len(X_train_cnn) // 32,
    epochs=30,
    validation_data=(X_test_cnn, y_test_cat),
    callbacks=[early_stop]
)

"""7. VGG16 TRANSFER LEARNING MODEL TRAINING"""

X_train_rgb = np.stack([np.stack([im.reshape(img_size)]*3, axis=-1) for im in X_train])
X_test_rgb = np.stack([np.stack([im.reshape(img_size)]*3, axis=-1) for im in X_test])

base_model = VGG16(weights='imagenet', include_top=False, input_shape=(64, 64, 3))
base_model.trainable = False

tl_model = models.Sequential([
    base_model,
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(class_names), activation='softmax')
])

tl_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Initial training (frozen base)
tl_history = tl_model.fit(
    datagen.flow(preprocess_input(X_train_rgb.astype(np.float32)), y_train_cat, batch_size=32),
    steps_per_epoch=len(X_train_rgb) // 32,
    epochs=10,
    validation_data=(preprocess_input(X_test_rgb.astype(np.float32)), y_test_cat),
    callbacks=[early_stop]
)

# Optional: Fine-tune top layers
base_model.trainable = True
for layer in base_model.layers[:-4]:
    layer.trainable = False

tl_model.compile(optimizer=tf.keras.optimizers.Adam(1e-5), loss='categorical_crossentropy', metrics=['accuracy'])
tl_model.fit(
    datagen.flow(preprocess_input(X_train_rgb.astype(np.float32)), y_train_cat, batch_size=32),
    steps_per_epoch=len(X_train_rgb) // 32,
    epochs=5,
    validation_data=(preprocess_input(X_test_rgb.astype(np.float32)), y_test_cat),
    callbacks=[early_stop]
)

""" 8. MODEL ENSEMBLE: PREDICTION (SOFT VOTING)"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

cnn_probs = cnn_model_func.predict(X_test_cnn)  # shape: (num_samples, num_classes)
tl_probs = tl_model.predict(preprocess_input(X_test_rgb.astype(np.float32)))  # shape: (num_samples, num_classes)

# Ensemble (Soft Voting)
ensemble_probs = (cnn_probs + tl_probs) / 2
ensemble_pred = np.argmax(ensemble_probs, axis=1)

# Evaluation
print("Hybrid Model (Ensemble) Accuracy:", accuracy_score(y_test, ensemble_pred))
print(classification_report(y_test, ensemble_pred, target_names=class_names))

cm = confusion_matrix(y_test, ensemble_pred)
sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix: Hybrid Model (Shallow CNN + VGG16 TL)')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

tl_pred = np.argmax(tl_model.predict(preprocess_input(X_test_rgb.astype(np.float32))), axis=1)
print("VGG16 Transfer Learning Accuracy:", accuracy_score(y_test, tl_pred))

cnn_pred = np.argmax(cnn_model_func.predict(X_test_cnn), axis=1)
print("CNN Accuracy:", accuracy_score(y_test, cnn_pred))

print("Hybrid Model (Ensemble) Accuracy:", accuracy_score(y_test, ensemble_pred))

"""# **SECTION 3: Explainability Module (Grad-CAM, SHAP, LIME, Deletion Curve, etc.)**

9. GRAD-CAM (FOR CNN, VGG16, AND ENSEMBLE)
"""

import cv2
from tensorflow.keras.applications.vgg16 import preprocess_input
def preprocess_cnn(x):
    x = x.astype("float32")
    return np.mean(x, axis=-1, keepdims=True) / 255.0  # Normalize grayscale

def preprocess_vgg(x):
    return preprocess_input(x.astype(np.float32))

# Define sample image for Grad-CAM
sample_img = X_test_rgb[0].astype("uint8")  # You can change the index to pick any image from the test set

def gradcam(model, img_rgb, conv_layer_name, preprocess_fn):
    img_prep = preprocess_fn(img_rgb.copy())
    img_prep = np.expand_dims(img_prep, 0)

    conv_layer = model.get_layer(conv_layer_name)

    grad_model = tf.keras.models.Model(
        [model.input],
        [conv_layer.output, model.output]
    )

    with tf.GradientTape() as tape:
        conv_out, preds = grad_model(img_prep)
        class_idx = tf.argmax(preds[0])
        loss = preds[:, class_idx]

    grads = tape.gradient(loss, conv_out)
    pooled = tf.reduce_mean(grads, axis=(0, 1, 2))
    conv_out = conv_out[0]

    heat = conv_out @ pooled[..., tf.newaxis]
    heat = np.squeeze(heat.numpy())
    heat = np.maximum(heat, 0)
    heat /= (heat.max() + 1e-8)

    heatmap = cv2.resize(heat, (img_rgb.shape[1], img_rgb.shape[0]))
    heatmap = cv2.applyColorMap(np.uint8(255 * heatmap), cv2.COLORMAP_JET)
    return heatmap

# VGG16 Grad-CAM
cam_vgg = gradcam(vgg_model_func, sample_img, "block5_conv3", preprocess_vgg)

# CNN Grad-CAM
cam_cnn = gradcam(cnn_model_func, sample_img, "conv2d_1", preprocess_cnn)

# Ensemble Grad-CAM
ensemble_cam = np.uint8((cam_vgg.astype("float32") + cam_cnn.astype("float32")) / 2)

"""10. SHAP — Image Masker for Ensemble"""

import shap

background_images = X_test_rgb[:50].astype("uint8")  # Use a batch of sample images as background
mean_background_img = np.mean(background_images, axis=0).astype("uint8")

# Initialize ImageMasker with a single averaged image as mask_value
masker = shap.maskers.Image(mean_background_img)

def ensemble_predict_uint8(imgs_uint8):
    imgs_uint8 = imgs_uint8.astype("float32")

    vgg_probs = vgg_model_func.predict(preprocess_vgg(imgs_uint8.copy()), verbose=0)

    cnn_probs = cnn_model_func.predict(preprocess_cnn(imgs_uint8.copy()), verbose=0)

    return 0.5 * vgg_probs + 0.5 * cnn_probs

# sample_img is already (64, 64, 3) from X_test_rgb[0].astype("uint8") defined in a previous cell.
explainer = shap.Explainer(ensemble_predict_uint8, masker)
shap_values = explainer(sample_img[None])  # Pass sample_img directly, adding a batch dimension
shap.image_plot(shap_values, sample_img[None]) # Also update here

sv = shap_values.values[0,...,np.argmax(ensemble_predict_uint8(sample_img[None])[0])]
shap_map = np.mean(np.abs(sv), axis=-1)
shap_map = (shap_map - shap_map.min())/(shap_map.max()-shap_map.min()+1e-8)

"""11. LIME (Stable Segmentation)"""

!pip install lime
from lime import lime_image
from skimage.segmentation import slic

explainer_lime = lime_image.LimeImageExplainer(random_state=42)

def lime_classifier(imgs):
    return ensemble_predict_uint8((imgs * 255).astype("uint8"))

lime_exp = explainer_lime.explain_instance(
    sample_img.astype("double"),
    lime_classifier,
    top_labels=1,
    num_samples=2000,
    hide_color=0,
    segmentation_fn=lambda x: slic(x, n_segments=60, compactness=10)
)

temp, mask = lime_exp.get_image_and_mask(
    lime_exp.top_labels[0],
    positive_only=True,
    num_features=8
)

plt.figure(figsize=(5,5))
plt.imshow(temp.astype("uint8"))
plt.title("LIME – Ensemble")
plt.axis("off")
plt.show()

"""12. DELETION CURVE + AUC"""

def deletion_curve(model_fn, img, importance, steps=50):
    img_mod = img.copy()
    flat = importance.flatten()
    order = np.argsort(flat)[::-1]
    cls = np.argmax(model_fn(img[None])[0])
    scores = []
    H,W = img.shape[:2]

    for k in np.linspace(0, len(order), steps, dtype=int):
        if k > 0:
            coords = np.unravel_index(order[:k], (H,W))
            img_mod[coords] = 0
        scores.append(model_fn(img_mod[None])[0][cls])
    return scores

scores = deletion_curve(ensemble_predict_uint8, sample_img, shap_map)
plt.plot(scores)
plt.title("Deletion Curve (SHAP – Ensemble)")
plt.xlabel("Pixels removed")
plt.ylabel("Class probability")
plt.show()

print("AUC =", np.trapz(scores))

"""13. DISAGREEMENT HEATMAP"""

disagree = np.abs(cam_vgg.astype("float32") - cam_cnn.astype("float32"))
disagree = (255 * (disagree - disagree.min())/(disagree.max() - disagree.min() + 1e-8)).astype("uint8")

plt.figure(figsize=(5,5))
plt.imshow(cv2.cvtColor(disagree, cv2.COLOR_BGR2RGB))
plt.title("Model Disagreement Heatmap")
plt.axis("off")
plt.show()

"""14. DISPLAY ALL GRAD-CAM RESULTS"""

plt.figure(figsize=(15,5))
plt.subplot(131); plt.title("VGG16 CAM"); plt.imshow(cv2.cvtColor(cam_vgg, cv2.COLOR_BGR2RGB)); plt.axis("off")
plt.subplot(132); plt.title("CNN CAM"); plt.imshow(cv2.cvtColor(cam_cnn, cv2.COLOR_BGR2RGB)); plt.axis("off")
plt.subplot(133); plt.title("Ensemble CAM"); plt.imshow(cv2.cvtColor(ensemble_cam, cv2.COLOR_BGR2RGB)); plt.axis("off")
plt.show()

"""# **Performance Comparison and Visualization**"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Predictions
cnn_pred = cnn_model_func.predict(X_test_cnn)
vgg_pred = vgg_model_func.predict(preprocess_input(X_test_rgb.astype(np.float32)))
ensemble_pred = np.argmax(0.5 * cnn_pred + 0.5 * vgg_pred, axis=1)

# Accuracy
cnn_accuracy = accuracy_score(y_test, np.argmax(cnn_pred, axis=1))
vgg_accuracy = accuracy_score(y_test, np.argmax(vgg_pred, axis=1))
ensemble_accuracy = accuracy_score(y_test, ensemble_pred)

# Precision, Recall, F1-Score
cnn_report = classification_report(y_test, np.argmax(cnn_pred, axis=1), target_names=class_names, output_dict=True)
vgg_report = classification_report(y_test, np.argmax(vgg_pred, axis=1), target_names=class_names, output_dict=True)
ensemble_report = classification_report(y_test, ensemble_pred, target_names=class_names, output_dict=True)

# AUC
fpr_cnn, tpr_cnn, _ = roc_curve(y_test, cnn_pred[:, 1])
fpr_vgg, tpr_vgg, _ = roc_curve(y_test, vgg_pred[:, 1])
fpr_ensemble, tpr_ensemble, _ = roc_curve(y_test, 0.5 * cnn_pred[:, 1] + 0.5 * vgg_pred[:, 1])

auc_cnn = auc(fpr_cnn, tpr_cnn)
auc_vgg = auc(fpr_vgg, tpr_vgg)
auc_ensemble = auc(fpr_ensemble, tpr_ensemble)

# Confusion Matrix for Ensemble Model
cm = confusion_matrix(y_test, ensemble_pred)
plt.figure(figsize=(6,6))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names, cmap="Blues")
plt.title('Confusion Matrix: Ensemble Model')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

# ROC Curve
plt.figure(figsize=(8,6))
plt.plot(fpr_cnn, tpr_cnn, label=f"CNN (AUC = {auc_cnn:.2f})")
plt.plot(fpr_vgg, tpr_vgg, label=f"VGG16 (AUC = {auc_vgg:.2f})")
plt.plot(fpr_ensemble, tpr_ensemble, label=f"Ensemble (AUC = {auc_ensemble:.2f})")
plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.legend(loc='lower right')
plt.show()

# Model Performance Comparison Bar Chart
accuracy = [cnn_accuracy, vgg_accuracy, ensemble_accuracy]
models = ['CNN', 'VGG16', 'Ensemble']

plt.figure(figsize=(8,6))
sns.barplot(x=models, y=accuracy, palette="Blues_d")
plt.title('Model Performance Comparison')
plt.ylabel('Accuracy')
plt.show()

# Loss vs. Epochs (Training History)
plt.plot(cnn_history.history['loss'], label='CNN Loss')
plt.plot(cnn_history.history['val_loss'], label='CNN Validation Loss')
plt.title('CNN Loss vs. Epochs')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

# Loss vs. Epochs (Training History)
plt.plot(tl_history.history['loss'], label='VGG16 Loss')
plt.plot(tl_history.history['val_loss'], label='VGG16 Validation Loss')
plt.title('VGG16 Loss vs. Epochs')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()